# Generated by Django 3.2.7 on 2021-09-04 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediasite', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
