# Generated by Django 3.2.6 on 2021-09-04 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediasite', '0006_auto_20210904_1616'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoModel',
        ),
    ]
